FROM mysql/mysql-server:8.0

ENV MYSQL_DATABASE=${MYSQL_DATABASE} \
  MYSQL_USER=${PMA_USER} \
  MYSQL_PASSWORD=${MYSQL_PASSWORD} \
  MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} \
  TZ=Asia/Tokyo

COPY ./my.cnf /etc/my.cnf
RUN chmod 644 /etc/my.cnf
RUN "mysql -u root -p${MYSQL_PASSWORD} ${MYSQL_DATABASE}"
RUN "GRANT ALL ON *.* TO phper;"